version: "3.9"
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-changemeplease}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-changemeplease1234}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-my-org}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-my-bucket}
    networks:
      - local_nw

  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - chronograf-storage:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME:-admin}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-changemeplease}
    networks:
      - local_nw

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-changemeplease}
    networks:
      - local_nw

  python-pinger:
    build:
      context: .
      dockerfile: python-ping/Dockerfile
    command: bash -c "poetry run python python_ping/main.py"
    networks:
    - local_nw
    environment:
      - INFLUXDB_ORG=${INFLUXDB_ORG:-my-org}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-my-bucket}
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN:-changemeplease1234}
      - INFLUXDB_HOSTNAME=influxdb
      - INFLUXDB_PORT=8086


volumes:
  influxdb-storage:
  chronograf-storage:
  grafana-storage:

networks:
  local_nw:
    driver: bridge
